import { Input, Text } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>After sale service (E-Claim)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Text variant={'mediumParagraph'}>Hello world</Text>
        <Input />
      </main>
    </>
  );
}
